import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  bottomNavigation: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "white",
    paddingVertical: 8,
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
    minHeight: 70,
  },
  navContainer: {
    flexDirection: "row",
    backgroundColor: "transparent",
    borderRadius: 0,
    paddingVertical: 0,
    paddingHorizontal: 0,
    shadowColor: "transparent",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
    borderWidth: 0,
    borderColor: "transparent",
    gap: 8,
    justifyContent: "space-between",
    alignItems: "center",
    flex: 1,
  },
  navItem: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 6,
    paddingHorizontal: 4,
    borderRadius: 12,
    flex: 1,
    minWidth: 60,
    maxWidth: 80,
    minHeight: 50,
  },
  navItemActive: {
    backgroundColor: "#eff6ff",
  },
  navLabel: {
    fontSize: 12,
    fontWeight: "500",
    color: "#9ca3af",
    textAlign: "center",
    marginTop: 4,
    lineHeight: 14,
    numberOfLines: 1,
  },
  navLabelActive: {
    color: "#007bff",
    fontWeight: "600",
  },
})