import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  calendarContainer: {
    backgroundColor: "white",
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginTop: 10,
    marginBottom: 20,
    marginHorizontal: 4,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: "#c7c7c7ff",
  },
  // Month Navigation Styles
  monthHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 4,
    paddingVertical: 12,
    marginBottom: 12,
  },
  monthNavButton: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  monthTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1e293b",
  },
  // Week Days Header
  weekDaysHeader: {
    flexDirection: "row",
    marginBottom: 12,
    backgroundColor: "#d8ecdcff",
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    gap: 4,
  },
  weekDayContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  weekDayLabel: {
    textAlign: "center",
    fontSize: 10,
    fontWeight: "600",
    color: "#475569",
    paddingVertical: 6,
    flex: 1,
  },
  weekDayDivider: {
    fontSize: 12,
    color: "#000000ff",
    fontWeight: "400",
    marginHorizontal: 4,
  },
  calendarDatesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    paddingHorizontal: 4,
  },
  dateCell: {
    width: "12.8%",
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    marginBottom: 4,
    position: "relative",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#cbcbccff",
  },
  dateCellOtherMonth: {
    opacity: 0.6,
    backgroundColor: "#f8fafc",
    borderColor: "#f1f5f9",
  },
  dateCellSelected: {
    backgroundColor: "#1e293b",
    borderColor: "#1e293b",
    shadowColor: "#1e293b",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  dateCellPast: {
    opacity: 0.7,
    backgroundColor: "#f8fafc",
    borderColor: "#e2e8f0",
  },
  dateCellText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1e293b",
  },
  dateCellTextOther: {
    color: "#64748b",
    fontWeight: "500",
  },
  dateCellTextSelected: {
    color: "white",
    fontWeight: "700",
  },
  dateCellTextPast: {
    color: "#64748b",
    fontWeight: "500",
  },
  reservationDot: {
    position: "absolute",
    bottom: 4,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#ec4899",
    shadowColor: "#ec4899",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 2,
  },
  facilityDotsContainer: {
    position: "absolute",
    bottom: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  facilityDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 2,
  },
  coveredCourtDot: {
    backgroundColor: "#3b82f6", // Blue for Covered Court
    shadowColor: "#3b82f6",
  },
  multiPurposeHallDot: {
    backgroundColor: "#f59e0b", // Orange for Multi Purpose Hall
    shadowColor: "#f59e0b",
  },
  otherFacilityDot: {
    backgroundColor: "#10b981", // Green for other facilities
    shadowColor: "#10b981",
  },
  legendContainer: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
  },
  legendTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: "#64748b",
    marginBottom: 8,
  },
  legendRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 1,
    elevation: 1,
  },
  legendText: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: "500",
  },
})