import { StyleSheet } from "react-native"

export const modalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    paddingTop: 0,
  },
  
  // Info Modal
  infoModal: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
    width: "100%",
    maxWidth: 340,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  infoModalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1a1a1a",
    marginTop: 16,
    marginBottom: 8,
    textAlign: "center",
  },
  infoModalText: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 20,
  },
  infoModalButton: {
    backgroundColor: "#2d1b2e",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 10,
    width: "100%",
  },
  infoModalButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  
  // Confirmation Modal
  confirmModal: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
    width: "100%",
    maxWidth: 380,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  confirmHeader: {
    alignItems: "center",
    marginBottom: 20,
  },
  confirmTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#1a1a1a",
    marginTop: 12,
    marginBottom: 8,
  },
  warningBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF3CD',
    borderLeftWidth: 4,
    borderLeftColor: '#FF9500',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
    gap: 10,
  },
  warningText: {
    flex: 1,
    fontSize: 13,
    color: '#856404',
    lineHeight: 18,
    fontWeight: '500',
  },
  confirmDetails: {
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    gap: 12,
  },
  confirmRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  confirmLabel: {
    fontSize: 13,
    color: "#666",
    fontWeight: "500",
  },
  confirmValue: {
    fontSize: 14,
    color: "#1a1a1a",
    fontWeight: "600",
    flex: 1,
    textAlign: "right",
  },
  confirmAmountRow: {
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: 2,
    borderTopColor: "#e0e0e0",
  },
  confirmAmountLabel: {
    fontSize: 14,
    color: "#666",
    fontWeight: "600",
  },
  confirmAmountValue: {
    fontSize: 20,
    color: "#2d1b2e",
    fontWeight: "bold",
  },
  confirmActions: {
    flexDirection: "row",
    gap: 12,
  },
  confirmCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: "#f0f0f0",
    alignItems: "center",
  },
  confirmCancelText: {
    fontSize: 15,
    color: "#666",
    fontWeight: "600",
  },
  confirmPayButton: {
    flex: 1,
    borderRadius: 10,
    overflow: "hidden",
  },
  confirmPayGradient: {
    paddingVertical: 14,
    alignItems: "center",
  },
  confirmPayText: {
    fontSize: 15,
    color: "#fff",
    fontWeight: "bold",
  },
  
  // Cash Receipt Modal - COMPACT VERSION
  cashReceiptModal: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    width: "100%",
    maxWidth: 380,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 10,
  },
  cashReceiptHeader: {
    alignItems: "center",
    marginBottom: 16,
  },
  cashReceiptTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1a1a1a",
    marginTop: 8,
    marginBottom: 2,
    textAlign: "center",
  },
  cashReceiptSubtitle: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
  },
  warningBox: {
    backgroundColor: "#FFF3CD",
    borderLeftWidth: 4,
    borderLeftColor: "#FF3B30",
    borderRadius: 8,
    padding: 10,
    marginBottom: 14,
  },
  warningBoxHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 4,
  },
  warningBoxTitle: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#856404",
  },
  warningBoxText: {
    fontSize: 11,
    color: "#856404",
    lineHeight: 16,
  },
  warningBoxHighlight: {
    fontWeight: "bold",
    color: "#FF3B30",
    fontSize: 12,
  },
  receiptDetails: {
    backgroundColor: "#f8f9fa",
    borderRadius: 10,
    padding: 12,
    marginBottom: 14,
    gap: 8,
  },
  receiptDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  receiptDetailText: {
    fontSize: 13,
    color: "#1a1a1a",
    flex: 1,
    fontWeight: "500",
  },
  instructionsBox: {
    backgroundColor: "#E8F5E9",
    borderLeftWidth: 4,
    borderLeftColor: "#00C853",
    borderRadius: 8,
    padding: 10,
    marginBottom: 16,
  },
  instructionsTitle: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#1B5E20",
    marginBottom: 6,
  },
  instructionsText: {
    fontSize: 11,
    color: "#2E7D32",
    lineHeight: 17,
  },
  cashReceiptActions: {
    gap: 12,
  },
  cashReceiptActionsRow: {
    flexDirection: "row",
    gap: 8,
  },
  downloadButton: {
    flex: 1,
    borderRadius: 10,
    overflow: "hidden",
    shadowColor: "#007DFF",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  downloadButtonGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 13,
    gap: 6,
  },
  downloadButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
  },
  doneButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    gap: 5,
    backgroundColor: "#f5f5f5",
    borderRadius: 10,
  },
  doneButtonText: {
    color: "#2d1b2e",
    fontSize: 13,
    fontWeight: "600",
  },
  closeButton: {
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  closeButtonText: {
    color: "#666",
    fontSize: 14,
    fontWeight: "600",
  },
  
  // Success Modal
  successModal: {
    backgroundColor: "#fff",
    borderRadius: 24,
    padding: 28,
    width: "100%",
    maxWidth: 380,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 12,
  },
  successIconContainer: {
    marginBottom: 16,
  },
  successTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#1a1a1a",
    marginBottom: 8,
    textAlign: "center",
  },
  successSubtitle: {
    fontSize: 15,
    color: "#666",
    marginBottom: 24,
    textAlign: "center",
  },
  successDetails: {
    width: "100%",
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    gap: 12,
  },
  successDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  successDetailText: {
    fontSize: 14,
    color: "#1a1a1a",
    flex: 1,
  },
  successButton: {
    width: "100%",
    borderRadius: 12,
    overflow: "hidden",
    shadowColor: "#2d1b2e",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  successButtonGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    gap: 8,
  },
  successButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  
  // Confetti
  confetti: {
    position: "absolute",
    width: 10,
    height: 10,
    borderRadius: 5,
    top: "50%",
    left: "50%",
  },
})