import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  header: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#f8fafc",
  },
  headerTitle: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: "600",
    color: "#64748b",
  },
  monthHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: "#f8fafc",
  },
  monthNavButton: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  monthNavText: {
    fontSize: 24,
    color: "#64748b",
    fontWeight: "400",
  },
  monthTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1e293b",
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
  },
  calendarContainer: {
    backgroundColor: "white",
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 20,
    marginHorizontal: 4,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: "#c7c7c7ff",
  },
  weekDaysHeader: {
    flexDirection: "row",
    marginBottom: 12,
    backgroundColor: "#d8ecdcff",
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    gap: 4,
  },
  weekDayContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  weekDayLabel: {
    textAlign: "center",
    fontSize: 10,
    fontWeight: "600",
    color: "#475569",
    paddingVertical: 6,
    flex: 1,
  },
  weekDayDivider: {
    fontSize: 12,
    color: "#000000ff",
    fontWeight: "400",
    marginHorizontal: 4,
  },
  calendarDatesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    paddingHorizontal: 4,
  },
  dateCell: {
    width: "12.8%",
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    marginBottom: 4,
    position: "relative",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#cbcbccff",
  },
  dateCellOtherMonth: {
    opacity: 0.6,
    backgroundColor: "#f8fafc",
    borderColor: "#f1f5f9",
  },
  dateCellSelected: {
    backgroundColor: "#1e293b",
    borderColor: "#1e293b",
    shadowColor: "#1e293b",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  dateCellPast: {
    opacity: 0.7,
    backgroundColor: "#f8fafc",
    borderColor: "#e2e8f0",
  },
  dateCellText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1e293b",
  },
  dateCellTextOther: {
    color: "#64748b",
    fontWeight: "500",
  },
  dateCellTextSelected: {
    color: "white",
    fontWeight: "700",
  },
  dateCellTextPast: {
    color: "#64748b",
    fontWeight: "500",
  },
  reservationDot: {
    position: "absolute",
    bottom: 4,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#ec4899",
    shadowColor: "#ec4899",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 2,
  },
  eventsSection: {
    marginBottom: 20,
  },
  eventsHeaderContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  eventsHeader: {
    fontSize: 20,
    color: "#1e293b",
    fontWeight: "600",
  },
  viewAllText: {
    fontSize: 14,
    color: "#94a3b8",
    fontWeight: "500",
  },
  eventsList: {
    gap: 12,
  },
  eventItem: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  eventDateBadge: {
    width: 48,
    height: 48,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  eventDateDay: {
    fontSize: 16,
    fontWeight: "700",
    color: "white",
    lineHeight: 18,
  },
  eventDateMonth: {
    fontSize: 10,
    fontWeight: "600",
    color: "white",
    lineHeight: 12,
  },
  eventContent: {
    flex: 1,
  },
  eventTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1e293b",
    marginBottom: 8,
  },
  eventTimeContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  playButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#3b82f6",
    alignItems: "center",
    justifyContent: "center",
  },
  playButtonText: {
    fontSize: 8,
    color: "white",
    marginLeft: 1,
  },
  progressBar: {
    flex: 1,
    height: 4,
    backgroundColor: "#e2e8f0",
    borderRadius: 2,
    marginHorizontal: 8,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#3b82f6",
    borderRadius: 2,
  },
  eventTime: {
    fontSize: 12,
    color: "#94a3b8",
    fontWeight: "500",
  },
  emptyState: {
    backgroundColor: "white",
    padding: 24,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  emptyStateText: {
    fontSize: 14,
    color: "#64748b",
    textAlign: "center",
  },
  facilitySelector: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
  },
  facilityScrollContainer: {
    alignItems: "center",
    justifyContent: "center",
  },
  facilityButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginHorizontal: 4,
    borderRadius: 20,
    backgroundColor: "#e2e8f0",
  },
  facilityButtonSelected: {
    backgroundColor: "#3b82f6",
  },
  facilityButtonText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#64748b",
  },
  facilityButtonTextSelected: {
    color: "white",
  },
  newEventItem: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 12,
  },
  eventIconContainer: {
    marginRight: 16,
  },
  eventAppIcon: {
    width: 48,
    height: 48,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  eventAppIconText: {
    fontSize: 16,
    fontWeight: "700",
    color: "white",
  },
  newEventContent: {
    flex: 1,
  },
  newEventTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1e293b",
    marginBottom: 4,
  },
  newEventSubtitle: {
    fontSize: 14,
    color: "#64748b",
    marginBottom: 8,
  },
  newEventTimeBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  newEventTimeText: {
    fontSize: 12,
    fontWeight: "600",
    color: "white",
  },
  bottomNavigation: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "white",
    paddingVertical: 8,
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
    minHeight: 70,
  },
  navContainer: {
    flexDirection: "row",
    backgroundColor: "transparent",
    borderRadius: 0,
    paddingVertical: 0,
    paddingHorizontal: 0,
    shadowColor: "transparent",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
    borderWidth: 0,
    borderColor: "transparent",
    gap: 8,
    justifyContent: "space-between",
    alignItems: "center",
    flex: 1,
  },
  navItem: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 6,
    paddingHorizontal: 4,
    borderRadius: 12,
    flex: 1,
    minWidth: 60,
    maxWidth: 80,
    minHeight: 50,
  },
  navItemActive: {
    backgroundColor: "#eff6ff",
  },
  navLabel: {
    fontSize: 12,
    fontWeight: "500",
    color: "#9ca3af",
    textAlign: "center",
    marginTop: 4,
    lineHeight: 14,
    numberOfLines: 1,
  },
  navLabelActive: {
    color: "#007bff",
    fontWeight: "600",
  },
})
